"""Guess the Character — three clues each, hardest first. The player sees
clue 1, may reveal clue 2 and 3 (fewer clues used = more XP), then picks
the name from four. Names follow the Tamil BSI (Union) spelling."""

CHARACTERS = [
	{"key": "noah", "en": "Noah", "ta": "நோவா", "ref": "Genesis 6–9",
	 "clues_en": ["I was 600 years old when a great event began.", "I sent out a raven and then a dove.", "I built an ark and saved my family from the flood."],
	 "clues_ta": ["ஒரு பெரிய சம்பவம் தொடங்கியபோது எனக்கு 600 வயது.", "நான் ஒரு காகத்தையும் பின்பு ஒரு புறாவையும் அனுப்பினேன்.", "நான் பேழையைக் கட்டி, என் குடும்பத்தை ஜலப்பிரளயத்திலிருந்து காப்பாற்றினேன்."]},
	{"key": "abraham", "en": "Abraham", "ta": "ஆபிரகாம்", "ref": "Genesis 12–22",
	 "clues_en": ["I left Ur of the Chaldees without knowing where I was going.", "God changed my name and promised me descendants like the stars.", "I was ready to offer my son Isaac on Mount Moriah."],
	 "clues_ta": ["எங்கே போகிறேன் என்று அறியாமல் கல்தேயரின் ஊர் பட்டணத்தை விட்டுப் புறப்பட்டேன்.", "தேவன் என் பெயரை மாற்றி, நட்சத்திரங்களைப்போல சந்ததியை வாக்களித்தார்.", "மோரியா மலையில் என் மகன் ஈசாக்கைப் பலியிட ஆயத்தமானேன்."]},
	{"key": "sarah", "en": "Sarah", "ta": "சாராள்", "ref": "Genesis 18, 21",
	 "clues_en": ["My name was changed from Sarai.", "I laughed when I heard I would have a child in old age.", "I am the mother of Isaac and the wife of Abraham."],
	 "clues_ta": ["என் பெயர் சாராய் என்பதிலிருந்து மாற்றப்பட்டது.", "முதிர்வயதில் பிள்ளை பிறக்கும் என்று கேட்டபோது நகைத்தேன்.", "நான் ஈசாக்கின் தாய், ஆபிரகாமின் மனைவி."]},
	{"key": "jacob", "en": "Jacob", "ta": "யாக்கோபு", "ref": "Genesis 25–35",
	 "clues_en": ["I dreamed of a ladder reaching to heaven.", "I wrestled with God and my name became Israel.", "I bought my brother Esau's birthright with a bowl of stew."],
	 "clues_ta": ["வானத்தை எட்டும் ஏணியைக் கனவில் கண்டேன்.", "தேவனோடு போராடினேன்; என் பெயர் இஸ்ரவேல் ஆனது.", "ஒரு கூழுக்கு என் சகோதரன் ஏசாவின் சேஷ்டபுத்திர பாகத்தை வாங்கினேன்."]},
	{"key": "joseph", "en": "Joseph", "ta": "யோசேப்பு", "ref": "Genesis 37–50",
	 "clues_en": ["I was thrown into a pit and then into a prison.", "I explained Pharaoh's dreams about cows and grain.", "My father gave me a coat of many colours."],
	 "clues_ta": ["என்னைக் குழியிலும் பின்பு சிறைச்சாலையிலும் போட்டார்கள்.", "பசுக்களையும் கதிர்களையும் பற்றிய பார்வோனின் சொப்பனங்களுக்கு அர்த்தம் சொன்னேன்.", "என் தகப்பன் எனக்குப் பலவர்ண அங்கியைக் கொடுத்தார்."]},
	{"key": "moses", "en": "Moses", "ta": "மோசே", "ref": "Exodus 2–14",
	 "clues_en": ["As a baby I was hidden in a basket among the reeds.", "God spoke to me from a burning bush.", "I led Israel out of Egypt through the Red Sea."],
	 "clues_ta": ["குழந்தையாயிருந்தபோது நாணல்களுக்குள் ஒரு பெட்டியில் ஒளித்து வைக்கப்பட்டேன்.", "எரியும் முட்செடியிலிருந்து தேவன் என்னோடு பேசினார்.", "இஸ்ரவேலரைச் சிவந்த சமுத்திரத்தின் வழியாய் எகிப்திலிருந்து நடத்தினேன்."]},
	{"key": "aaron", "en": "Aaron", "ta": "ஆரோன்", "ref": "Exodus 4, 28, 32",
	 "clues_en": ["My rod budded, blossomed and gave almonds.", "I made a golden calf while my brother was on the mountain.", "I was Israel's first high priest and Moses' brother."],
	 "clues_ta": ["என் கோல் துளிர்த்துப் பூத்து வாதுமைப்பழங்களைக் கொடுத்தது.", "என் சகோதரன் மலையில் இருந்தபோது பொன் கன்றுக்குட்டியை உண்டாக்கினேன்.", "நான் இஸ்ரவேலின் முதல் பிரதான ஆசாரியன், மோசேயின் சகோதரன்."]},
	{"key": "joshua", "en": "Joshua", "ta": "யோசுவா", "ref": "Joshua 1–6",
	 "clues_en": ["I was one of the twelve spies who gave a good report.", "I was told: be strong and of a good courage.", "The walls of Jericho fell when my people shouted."],
	 "clues_ta": ["நல்ல அறிக்கை கொடுத்த பன்னிரண்டு வேவுகாரரில் நானும் ஒருவன்.", "பலங்கொண்டு திடமனதாயிரு என்று எனக்குச் சொல்லப்பட்டது.", "என் ஜனங்கள் ஆர்ப்பரித்தபோது எரிகோவின் மதில்கள் விழுந்தன."]},
	{"key": "rahab", "en": "Rahab", "ta": "ராகாப்", "ref": "Joshua 2, 6",
	 "clues_en": ["I lived in a house built on a city wall.", "I hid two spies under stalks of flax on my roof.", "A scarlet cord in my window saved my family in Jericho."],
	 "clues_ta": ["பட்டணத்தின் மதிலின்மேல் கட்டப்பட்ட வீட்டில் வாழ்ந்தேன்.", "இரண்டு வேவுகாரரை என் மாடியில் சணல் தட்டைகளின் கீழ் ஒளித்து வைத்தேன்.", "என் ஜன்னலில் கட்டிய சிவப்புக் கயிறு எரிகோவில் என் குடும்பத்தைக் காப்பாற்றியது."]},
	{"key": "gideon", "en": "Gideon", "ta": "கிதியோன்", "ref": "Judges 6–7",
	 "clues_en": ["I was threshing wheat in a winepress when an angel came.", "I asked for a sign with a fleece of wool.", "God won a battle through my 300 men with trumpets and jars."],
	 "clues_ta": ["தூதன் வந்தபோது ஆலையில் கோதுமையைப் போரடித்துக்கொண்டிருந்தேன்.", "ஆட்டுமயிர்த் தோலைக்கொண்டு அடையாளம் கேட்டேன்.", "எக்காளங்களும் பானைகளும் கொண்ட என் 300 பேரைக்கொண்டு தேவன் யுத்தத்தை ஜெயித்தார்."]},
	{"key": "samson", "en": "Samson", "ta": "சிம்சோன்", "ref": "Judges 13–16",
	 "clues_en": ["I killed a lion with my bare hands.", "I was a Nazirite from birth; no razor touched my head.", "Delilah found the secret of my great strength."],
	 "clues_ta": ["வெறுங்கையால் ஒரு சிங்கத்தைக் கொன்றேன்.", "பிறப்பிலிருந்தே நசரேயன்; என் தலையில் சவரகன் கத்தி படவில்லை.", "என் மகா பலத்தின் இரகசியத்தைத் தெலீலாள் கண்டுபிடித்தாள்."]},
	{"key": "ruth", "en": "Ruth", "ta": "ரூத்", "ref": "Ruth 1–4",
	 "clues_en": ["I was a Moabite widow.", "I gleaned barley in the field of Boaz.", "I told Naomi: thy people shall be my people."],
	 "clues_ta": ["நான் மோவாபிய விதவை.", "போவாசின் வயலில் வாற்கோதுமைக் கதிர் பொறுக்கினேன்.", "உம்முடைய ஜனம் என்னுடைய ஜனம் என்று நகோமியிடம் சொன்னேன்."]},
	{"key": "hannah", "en": "Hannah", "ta": "அன்னாள்", "ref": "1 Samuel 1–2",
	 "clues_en": ["Eli thought I was drunk while I prayed silently.", "I made a little coat for my son every year.", "I prayed for a son and gave him to the Lord — Samuel."],
	 "clues_ta": ["நான் மௌனமாய் ஜெபித்தபோது ஏலி என்னை வெறிகொண்டவள் என்று நினைத்தான்.", "ஒவ்வொரு வருஷமும் என் மகனுக்கு ஒரு சிறிய சட்டையை உண்டாக்கினேன்.", "ஒரு மகனுக்காக ஜெபித்து, அவனைக் கர்த்தருக்கு ஒப்புக்கொடுத்தேன் — சாமுவேல்."]},
	{"key": "samuel", "en": "Samuel", "ta": "சாமுவேல்", "ref": "1 Samuel 3, 16",
	 "clues_en": ["As a boy I served in the temple with Eli.", "I anointed both Saul and David as king.", "I heard my name called at night and answered: Speak, Lord."],
	 "clues_ta": ["சிறுவனாக ஏலியோடு ஆலயத்தில் ஊழியம் செய்தேன்.", "சவுலையும் தாவீதையும் ராஜாவாக அபிஷேகம் பண்ணினேன்.", "இரவில் என் பெயர் அழைக்கப்பட்டபோது: சொல்லும், அடியேன் கேட்கிறேன் என்றேன்."]},
	{"key": "david", "en": "David", "ta": "தாவீது", "ref": "1 Samuel 16–17",
	 "clues_en": ["I played the harp to calm a troubled king.", "I wrote many of the Psalms.", "As a shepherd boy I defeated Goliath with a sling and a stone."],
	 "clues_ta": ["கலங்கிய ராஜாவை அமைதிப்படுத்தச் சுரமண்டலம் வாசித்தேன்.", "பல சங்கீதங்களை எழுதினேன்.", "மேய்ப்பச் சிறுவனாக, கவணும் கல்லும் கொண்டு கோலியாத்தை வென்றேன்."]},
	{"key": "solomon", "en": "Solomon", "ta": "சாலொமோன்", "ref": "1 Kings 3–10",
	 "clues_en": ["The Queen of Sheba came to test me with hard questions.", "I built the first temple in Jerusalem.", "God offered me anything; I asked for wisdom."],
	 "clues_ta": ["சேபாவின் ராஜஸ்திரீ கடினமான கேள்விகளால் என்னைச் சோதிக்க வந்தாள்.", "எருசலேமில் முதல் தேவாலயத்தைக் கட்டினேன்.", "தேவன் எதைக் கேட்டாலும் தருவேன் என்றார்; நான் ஞானத்தைக் கேட்டேன்."]},
	{"key": "elijah", "en": "Elijah", "ta": "எலியா", "ref": "1 Kings 17–18; 2 Kings 2",
	 "clues_en": ["Ravens brought me bread and meat by a brook.", "Fire fell from heaven on my sacrifice at Mount Carmel.", "I was taken up to heaven in a whirlwind with a chariot of fire."],
	 "clues_ta": ["ஒரு ஆற்றண்டையில் காகங்கள் எனக்கு அப்பமும் இறைச்சியும் கொண்டுவந்தன.", "கர்மேல் மலையில் என் பலியின்மேல் வானத்திலிருந்து அக்கினி இறங்கியது.", "அக்கினி இரதத்தோடே சுழல்காற்றில் பரலோகத்துக்கு எடுத்துக்கொள்ளப்பட்டேன்."]},
	{"key": "esther", "en": "Esther", "ta": "எஸ்தர்", "ref": "Esther 2–7",
	 "clues_en": ["My cousin Mordecai raised me.", "I fasted three days before going to the king uninvited.", "I became queen of Persia and saved my people from Haman."],
	 "clues_ta": ["என் பெரியப்பா மகன் மொர்தெகாய் என்னை வளர்த்தான்.", "அழைப்பில்லாமல் ராஜாவினிடம் போகுமுன் மூன்று நாள் உபவாசித்தேன்.", "பெர்சியாவின் ராஜாத்தியாகி, ஆமானிடமிருந்து என் ஜனங்களைக் காப்பாற்றினேன்."]},
	{"key": "job", "en": "Job", "ta": "யோபு", "ref": "Job 1–2, 42",
	 "clues_en": ["Three friends came to comfort me but argued with me.", "I lost my children, my wealth and my health in a short time.", "I said: the LORD gave, and the LORD hath taken away."],
	 "clues_ta": ["மூன்று சிநேகிதர் ஆறுதல் சொல்ல வந்து என்னோடு வாதாடினார்கள்.", "சிறிது காலத்தில் என் பிள்ளைகளையும் செல்வத்தையும் சுகத்தையும் இழந்தேன்.", "கர்த்தர் கொடுத்தார், கர்த்தர் எடுத்தார் என்றேன்."]},
	{"key": "daniel", "en": "Daniel", "ta": "தானியேல்", "ref": "Daniel 1, 5, 6",
	 "clues_en": ["I refused the king's meat and ate vegetables instead.", "I read the writing on the wall for King Belshazzar.", "I was thrown into a den of lions and God shut their mouths."],
	 "clues_ta": ["ராஜாவின் போஜனத்தை மறுத்து, சாகபதார்த்தங்களைப் புசித்தேன்.", "பெல்ஷாத்சார் ராஜாவுக்குச் சுவரில் எழுதப்பட்ட எழுத்தை வாசித்தேன்.", "சிங்கங்களின் கெபியில் போடப்பட்டேன்; தேவன் அவைகளின் வாயைக் கட்டினார்."]},
	{"key": "jonah", "en": "Jonah", "ta": "யோனா", "ref": "Jonah 1–4",
	 "clues_en": ["I was upset when God spared a great city.", "I ran from God on a ship bound for Tarshish.", "A great fish swallowed me for three days and three nights."],
	 "clues_ta": ["தேவன் ஒரு பெரிய பட்டணத்தை மன்னித்தபோது நான் எரிச்சலடைந்தேன்.", "தர்ஷீசுக்குப் போகும் கப்பலில் தேவனைவிட்டு ஓடினேன்.", "ஒரு பெரிய மீன் என்னை மூன்று நாள் இரவும் பகலும் விழுங்கியிருந்தது."]},
	{"key": "mary", "en": "Mary", "ta": "மரியாள்", "ref": "Luke 1–2",
	 "clues_en": ["The angel Gabriel visited me in Nazareth.", "I was engaged to a carpenter named Joseph.", "I am the mother of Jesus."],
	 "clues_ta": ["நாசரேத்தில் காபிரியேல் தூதன் என்னைச் சந்தித்தான்.", "தச்சனாகிய யோசேப்புக்கு நியமிக்கப்பட்டிருந்தேன்.", "நான் இயேசுவின் தாய்."]},
	{"key": "john_baptist", "en": "John the Baptist", "ta": "யோவான் ஸ்நானகன்", "ref": "Matthew 3",
	 "clues_en": ["I ate locusts and wild honey.", "I wore clothing of camel's hair in the wilderness.", "I baptized Jesus in the Jordan River."],
	 "clues_ta": ["வெட்டுக்கிளியும் காட்டுத்தேனும் என் ஆகாரம்.", "வனாந்தரத்தில் ஒட்டகமயிர் உடை அணிந்திருந்தேன்.", "யோர்தான் நதியில் இயேசுவுக்கு ஞானஸ்நானம் கொடுத்தேன்."]},
	{"key": "peter", "en": "Peter", "ta": "பேதுரு", "ref": "Matthew 14, 26; John 21",
	 "clues_en": ["I walked on water — until I looked at the waves.", "I denied knowing Jesus three times before the rooster crowed.", "I was a fisherman; Jesus named me the rock."],
	 "clues_ta": ["அலைகளைப் பார்க்கும்வரை தண்ணீரின்மேல் நடந்தேன்.", "சேவல் கூவுமுன் இயேசுவை அறியேன் என்று மூன்றுதரம் மறுதலித்தேன்.", "நான் ஒரு மீன்பிடிக்கிறவன்; இயேசு எனக்குக் கல் என்று பெயரிட்டார்."]},
	{"key": "zacchaeus", "en": "Zacchaeus", "ta": "சகேயு", "ref": "Luke 19",
	 "clues_en": ["I was a rich chief tax collector in Jericho.", "I promised to give half my goods to the poor.", "Being short, I climbed a sycamore tree to see Jesus."],
	 "clues_ta": ["எரிகோவில் ஐசுவரியமுள்ள ஆயக்காரருக்குத் தலைவனாயிருந்தேன்.", "என் ஆஸ்திகளில் பாதியை ஏழைகளுக்குக் கொடுப்பேன் என்றேன்.", "குள்ளனாயிருந்ததால் இயேசுவைப் பார்க்க ஒரு காட்டத்தி மரத்தில் ஏறினேன்."]},
	{"key": "lazarus", "en": "Lazarus", "ta": "லாசரு", "ref": "John 11",
	 "clues_en": ["My sisters were Martha and Mary.", "I lived in Bethany.", "Jesus called me out of my tomb after four days."],
	 "clues_ta": ["மார்த்தாளும் மரியாளும் என் சகோதரிகள்.", "நான் பெத்தானியாவில் வாழ்ந்தேன்.", "நாலு நாள் கழித்து இயேசு என்னைக் கல்லறையிலிருந்து வெளியே அழைத்தார்."]},
	{"key": "thomas", "en": "Thomas", "ta": "தோமா", "ref": "John 20",
	 "clues_en": ["I was also called Didymus, the twin.", "I said I would not believe unless I saw the nail prints.", "When I saw the risen Jesus I said: My Lord and my God."],
	 "clues_ta": ["திதிமு என்னப்பட்டவன் நான்.", "ஆணிகளின் காயத்தைக் காணாவிட்டால் விசுவாசிக்கமாட்டேன் என்றேன்.", "உயிர்த்த இயேசுவைக் கண்டபோது: என் ஆண்டவரே! என் தேவனே! என்றேன்."]},
	{"key": "stephen", "en": "Stephen", "ta": "ஸ்தேவான்", "ref": "Acts 6–7",
	 "clues_en": ["I was chosen as one of seven to serve the widows.", "My face looked like the face of an angel before the council.", "I was the first Christian martyr, stoned while praying for my killers."],
	 "clues_ta": ["விதவைகளுக்கு ஊழியம் செய்ய ஏழு பேரில் ஒருவனாகத் தெரிந்துகொள்ளப்பட்டேன்.", "ஆலோசனைச் சங்கத்தின் முன் என் முகம் தேவதூதனுடைய முகம்போல் இருந்தது.", "என்னைக் கொன்றவர்களுக்காக ஜெபித்துக்கொண்டே கல்லெறியப்பட்ட முதல் இரத்தசாட்சி."]},
	{"key": "paul", "en": "Paul", "ta": "பவுல்", "ref": "Acts 9, 16, 27",
	 "clues_en": ["I was shipwrecked on the island of Malta.", "I sang hymns in a Philippian prison at midnight.", "A light blinded me on the road to Damascus."],
	 "clues_ta": ["மெலித்தா தீவின் அருகே கப்பற்சேதத்தில் அகப்பட்டேன்.", "பிலிப்பு பட்டணத்துச் சிறையில் நடுராத்திரியில் பாடினேன்.", "தமஸ்குவுக்குப் போகும் வழியில் ஒரு ஒளி என்னைக் குருடாக்கியது."]},
	{"key": "lydia", "en": "Lydia", "ta": "லீதியாள்", "ref": "Acts 16",
	 "clues_en": ["I came from the city of Thyatira.", "I sold purple cloth.", "The Lord opened my heart by a riverside in Philippi, and Paul stayed at my house."],
	 "clues_ta": ["நான் தியத்தீரா பட்டணத்தாள்.", "இரத்தாம்பர வியாபாரம் செய்தேன்.", "பிலிப்புவில் ஆற்றங்கரையில் கர்த்தர் என் இருதயத்தைத் திறந்தார்; பவுல் என் வீட்டில் தங்கினான்."]},
]
